DROP TABLE IF EXISTS license;

CREATE TABLE license (
    id INT AUTO_INCREMENT PRIMARY KEY ,
    license_id VARCHAR(10) NOT NULL ,
    description VARCHAR (100) NULL ,
    orgonization_id VARCHAR (10) NOT NULL,
    product_name VARCHAR (25) NOT NULL ,
    license_type VARCHAR (25) NULL );
-- ) as SELECT * FROM CSVREAD('test.csv')

/*
INSERT INTO license (license_id, description, orgonization_id, product_name, license_type) VALUES
('123450', 'THIS IS THE FIRST PRODUCT', '1230', 'SHAKTHI DHARMA', 'FULL' ),
('123451', 'THIS IS THE SECOND PRODUCT', '1231', 'SHAKTHI DHARMA', 'FULL' ),
('123452', 'THIS IS THE THIRD PRODUCT', '1232', 'SHAKTHI DHARMA', 'PARTIAL' ),
('123453', 'THIS IS THE 4TH PRODUCT', '1233', 'SHAKTHI DHARMA', 'FULL' ),
('123454', 'THIS IS THE 5TH PRODUCT', '1234', 'SHAKTHI DHARMA', 'PARTIAL' ),
('123455', 'THIS IS THE 6TH PRODUCT', '1235', 'SHAKTHI DHARMA', 'FULL' ),
('123456', 'THIS IS THE 7TH PRODUCT', '1236', 'SHAKTHI DHARMA', 'PARTIAL' ),
('123457', 'THIS IS THE 8TH PRODUCT', '1237', 'SHAKTHI DHARMA', 'FULL' ),
('123458', 'THIS IS THE 9TH PRODUCT', '1238', 'SHAKTHI DHARMA', 'PARTIAL' );
*
 */